development:
  adapter: postgresql
  database: public-transport
  pool: 5
  timeout: 5000
  username: kayvonghaffari

test:
  adapter: postgresql
  database: public-transport-test
  pool: 5
  timeout: 5000
  username: kayvonghaffari